### ISSUE TITLE
Strange implementation of BRK and JSR

### ISSUE THREAD

**Issue by ldm0** [whscullin/apple1js#33]
https://www.masswerk.at/6502/6502_instruction_set.html#BRK
https://www.masswerk.at/6502/6502_instruction_set.html#JSR

According to the documentation, BRK and JSR pushes PC + 2 to stack. 

But:
- https://github.com/whscullin/apple1js/blob/main/js/cpu6502.js#L458
- https://github.com/whscullin/apple1js/blob/main/js/cpu6502.js#L831

It seems that BRK pushes PC, and JSR pushes PC + 1 to stack.

**Comment by whscullin** [comment]
I'm not sure what they mean by PC + 2,  `readBytePC()` at the beginning increments the PC once more in addition to the initial increment after reading the opcode. This is in line with what is described in [Table 4.1](https://archive.org/details/Understanding_the_Apple_II_1983_Quality_Software/page/n81/mode/2up) in Jim Sather's Understanding the Apple II - and although admittedly BRK/RTI might not get exercised a whole lot, JSR/RTS simply wouldn't work any other way.

The 6502 code from sister project apple2js has been tested against the Tom Harte test suite that validates cycle and memory accuracy against a real CPU, the logic there, although re-written in Typescript, is unchanged.
