### ISSUE TITLE
Insert text from clipboard function

### ISSUE THREAD

**Issue by Eriknoc** [whscullin/apple1js#41]
Would like to see a function for inserting text from the clipboard into the emulator.
I think AppleWin's method (Shift+Insert) is pretty sensible.

**Comment by gabrielsroka** [comment]
Click Load, then paste the text there.

**Comment by whscullin** [comment]
You should be able to paste from the clipboard into the input buffer using whatever your browser considers to be the paste command (typically Windows ctrl-v, macOS command-v), and copy all on screen text with the copy command (typically Windows ctrl-c, macOS command-c).
